export default [
  {
    title: "Senior Software Developer",
    company: { title: "Lamoda", link: "https://lamoda.ru/" },
    years: "10.2019 - present",
    mainTech: ["Golang"],
    technologies: [
      "Kafka",
      "PostgreSQL",
      "Kubernetes",
      "Helm",
      "Python 3.6+",
      "Vue.js",
      "Django",
      "Reddis",
      "RabbitMQ",
      "NSQ",
      "ELK",
      "Icinga",
      "Docker",
      "Docker Compose",
    ],
    iconClass: "fa-brands fa-golang",
  },
  {
    title: "Python Developer",
    company: { title: "Tionix", link: "https://www.tionix.ru" },
    years: "09.2016 - 08.2018",
    mainTech: ["Python 2.7/3"],
    technologies: ["Python", "Django", "RabbitMQ", "MySQL", "Rest API", "SQLAlchemy", "Openstack"],
    iconClass: "fab fa-python",
  },
];
